-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 16:35:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_integrare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_integrare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_integrare` DEFAULT CHARACTER SET utf8 ;
USE `db_integrare` ;

-- -----------------------------------------------------
-- Table `db_integrare`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_integrare`.`tb_tema` (
  `id` BIGINT NOT NULL,
  `disciplinas` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrare`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_integrare`.`tb_usuario` (
  `id` BIGINT NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `nome_completo` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(1000) NULL,
  `tipo_usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_integrare`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_integrare`.`tb_postagem` (
  `id` BIGINT NOT NULL,
  `data` DATETIME(6) NOT NULL,
  `assunto` VARCHAR(100) NOT NULL,
  `texto_descricao` VARCHAR(1000) NOT NULL,
  `anexo` VARCHAR(1000) NULL,
  `tema_id` BIGINT NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagem_tb_tema_idx` (`tema_id` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_tema`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_integrare`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_integrare`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
